import Input from "@/components/form/input/InputField";
import BasicTableOne from "@/components/tables/BasicTableOne";
import Badge from "@/components/ui/badge/Badge";
import Button from "@/components/ui/button/Button";
import { sql } from "@/server/db";
import { setCustomerStatus } from "../actions";

export const dynamic="force-dynamic";const money=new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0});const date=new Intl.DateTimeFormat("en-KE",{dateStyle:"medium"});
export default async function CustomersPage({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){const {q="",status="all"}=await searchParams;const customers=await sql<{id:string;display_name:string|null;phone:string|null;email:string|null;status:"ACTIVE"|"SUSPENDED";orders:number;spent_minor:number;created_at:Date}[]>`SELECT u.id,u.display_name,u.phone,u.email,u.status::text,COUNT(o.id)::int AS orders,COALESCE(SUM(o.total_minor) FILTER(WHERE o.paid_at IS NOT NULL),0)::int AS spent_minor,u.created_at FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.role='CUSTOMER' AND (${q}='' OR u.display_name ILIKE ${`%${q}%`} OR u.phone ILIKE ${`%${q}%`} OR u.email::text ILIKE ${`%${q}%`}) AND (${status}='all' OR u.status::text=${status}) GROUP BY u.id ORDER BY u.created_at DESC LIMIT 100`;return <BasicTableOne title="Customers" description="Search accounts, review value, and control access." actions={<form className="flex gap-2"><Input name="q" defaultValue={q} placeholder="Name, phone or email"/><select name="status" defaultValue={status} className="h-11 rounded-lg border border-gray-300 bg-white px-3 text-sm dark:border-gray-700 dark:bg-gray-900"><option value="all">All customers</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select><Button type="submit" size="sm" variant="outline">Search & filter</Button></form>} columns={["Customer","Contact","Orders","Paid spend","Joined","Status","Action"]} empty="No customers match this search." rows={customers.map(c=>[<span key="n" className="font-medium text-gray-800 dark:text-white/90">{c.display_name||"Unnamed customer"}</span>,c.phone??c.email??"—",c.orders,money.format(c.spent_minor),date.format(c.created_at),<Badge key="s" size="sm" color={c.status==="ACTIVE"?"success":"warning"}>{c.status}</Badge>,<form key="a" action={setCustomerStatus.bind(null,c.id,c.status==="ACTIVE"?"SUSPENDED":"ACTIVE")}><Button type="submit" size="sm" variant="outline">{c.status==="ACTIVE"?"Suspend":"Reactivate"}</Button></form>])}/>}
