import ComponentCard from "@/components/common/ComponentCard";
import Input from "@/components/form/input/InputField";
import BasicTableOne from "@/components/tables/BasicTableOne";
import Badge from "@/components/ui/badge/Badge";
import Button from "@/components/ui/button/Button";
import PromotionActions from "@/components/admin/PromotionActions";
import { sql } from "@/server/db";
import { createPromotion } from "../actions";

export const dynamic="force-dynamic";
export default async function PromotionsPage({searchParams}:{searchParams:Promise<{notice?:string}>}){const {notice}=await searchParams;const promotions=await sql<{id:string;name:string;kind:string;value:string;code:string|null;usage_count:number;usage_limit:number|null;active:boolean;percentage_basis_points:number|null;minimum_order_minor:number|null}[]>`SELECT p.id,p.name,p.kind::text,CASE WHEN p.percentage_basis_points IS NOT NULL THEN (p.percentage_basis_points/100.0)::text||'%' WHEN p.amount_minor IS NOT NULL THEN 'KSh '||p.amount_minor::text ELSE 'Merchandising' END AS value,MIN(c.code::text) AS code,p.usage_count,p.usage_limit,p.active,p.percentage_basis_points,p.minimum_order_minor FROM promotions p LEFT JOIN coupons c ON c.promotion_id=p.id GROUP BY p.id ORDER BY p.created_at DESC`;const message=notice==='duplicate'?'That coupon code already exists. Use a different code or edit the existing promotion.':notice==='updated'?'Promotion updated.':notice==='created'?'Promotion created.':null;return <div className="space-y-6">{message?<p className={`rounded-lg px-4 py-3 text-sm ${notice==='duplicate'?'bg-amber-50 text-amber-900':'bg-green-50 text-green-900'}`}>{message}</p>:null}<ComponentCard title="Create promo code" desc="Percentage codes are validated by the same checkout pricing service."><form action={createPromotion} className="grid gap-4 md:grid-cols-4 md:items-end"><Input name="name" placeholder="Campaign name" required/><Input name="code" placeholder="Promo code" required/><Input name="percentage" type="number" min={1} max={100} placeholder="Discount %" required/><Input name="minimum" type="number" min={0} placeholder="Minimum order (KSh)" defaultValue={0}/><Button type="submit">Create promotion</Button></form></ComponentCard><BasicTableOne title="Promotions" description="Codes, discounts, availability, and redemption activity." columns={["Campaign","Type","Value","Code","Usage","Status","Actions"]} empty="No promotions configured." rows={promotions.map(p=>[<span key="n" className="font-medium text-gray-800">{p.name}</span>,p.kind,p.value,p.code??"—",`${p.usage_count} / ${p.usage_limit??'∞'}`,<Badge key="s" size="sm" color={p.active?"success":"light"}>{p.active?"Active":"Paused"}</Badge>,p.code?<PromotionActions key="a" id={p.id} name={p.name} code={p.code} percentage={(p.percentage_basis_points??0)/100} minimum={p.minimum_order_minor??0} active={p.active}/>:"—"] )}/></div>}
