import ComponentCard from "@/components/common/ComponentCard";
import Input from "@/components/form/input/InputField";
import BasicTableOne from "@/components/tables/BasicTableOne";
import Badge from "@/components/ui/badge/Badge";
import Button from "@/components/ui/button/Button";
import { sql } from "@/server/db";
import { createContentBlock,setContentActive } from "../actions";

export const dynamic="force-dynamic";
export default async function ContentPage(){const blocks=await sql<{id:string;key:string;kind:string;title:string|null;link_url:string|null;sort_order:number;active:boolean}[]>`SELECT id,key,kind,title,link_url,sort_order,active FROM content_blocks ORDER BY sort_order,created_at`;return <div className="space-y-6"><ComponentCard title="Add homepage content" desc="Manage banners and featured-product sections shown on the storefront."><form action={createContentBlock} className="grid gap-4 md:grid-cols-3"><select name="kind" className="h-11 rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900"><option value="HERO_BANNER">Homepage banner</option><option value="FEATURED_SECTION">Featured products</option></select><Input name="key" placeholder="Unique key" required/><Input name="title" placeholder="Title" required/><Input name="body" placeholder="Supporting copy"/><Input name="imageUrl" placeholder="Image URL"/><Input name="linkUrl" placeholder="Destination URL"/><div><Button type="submit">Publish content</Button></div></form></ComponentCard><BasicTableOne title="Store content" description="Homepage banners and merchandising content served to the storefront." columns={["Key","Type","Title","Destination","Order","Status","Action"]} empty="Homepage content blocks will appear here." rows={blocks.map(b=>[<span key="k" className="font-medium text-gray-800 dark:text-white/90">{b.key}</span>,b.kind,b.title??"—",b.link_url??"—",b.sort_order,<Badge key="s" size="sm" color={b.active?"success":"light"}>{b.active?"Published":"Hidden"}</Badge>,<form key="a" action={setContentActive.bind(null,b.id,!b.active)}><Button type="submit" size="sm" variant="outline">{b.active?"Hide":"Publish"}</Button></form>])}/></div>}
