import ComponentCard from "@/components/common/ComponentCard";
import Input from "@/components/form/input/InputField";
import BasicTableOne from "@/components/tables/BasicTableOne";
import Badge from "@/components/ui/badge/Badge";
import Button from "@/components/ui/button/Button";
import { sql } from "@/server/db";
import { createPurchaseOrder, createVendor, receivePurchaseOrder, recordVendorPayment } from "../actions";

export const dynamic = "force-dynamic";
const money = new Intl.NumberFormat("en-KE", { style:"currency", currency:"KES", maximumFractionDigits:0 });

export default async function VendorsPage({ searchParams }:{ searchParams:Promise<{q?:string}> }) {
  const { q="" } = await searchParams;
  const [vendors, orders, payments, variants] = await Promise.all([
    sql<{id:string;name:string;contact_name:string|null;phone:string|null;email:string|null;payment_terms:string|null;status:string;products:number;balance_minor:number}[]>`SELECT v.id,v.name,v.contact_name,v.phone,v.email::text,v.payment_terms,v.status,COUNT(vp.variant_id)::int AS products,v.balance_minor::int FROM vendors v LEFT JOIN vendor_products vp ON vp.vendor_id=v.id WHERE (${q}='' OR v.name ILIKE ${`%${q}%`} OR v.contact_name ILIKE ${`%${q}%`}) GROUP BY v.id ORDER BY v.name`,
    sql<{id:string;po_number:string;vendor:string;status:string;total_minor:number;ordered_at:Date|null;expected_at:Date|null}[]>`SELECT po.id,po.po_number,v.name AS vendor,po.status,po.total_minor,po.ordered_at,po.expected_at FROM purchase_orders po JOIN vendors v ON v.id=po.vendor_id ORDER BY po.created_at DESC LIMIT 30`,
    sql<{vendor:string;reference:string|null;amount_minor:number;status:string;paid_at:Date|null}[]>`SELECT v.name AS vendor,p.reference,p.amount_minor,p.status,p.paid_at FROM vendor_payments p JOIN vendors v ON v.id=p.vendor_id ORDER BY p.created_at DESC LIMIT 30`,
    sql<{id:string;label:string}[]>`SELECT pv.id,p.name||' · '||pv.label||' · '||pv.sku AS label FROM product_variants pv JOIN products p ON p.id=pv.product_id ORDER BY p.name,pv.label`,
  ]);
  return <div className="space-y-6">
    <ComponentCard title="Add supplier" desc="Suppliers can be linked to product variants and purchase orders."><form action={createVendor} className="grid gap-4 md:grid-cols-5 md:items-end"><Input name="name" placeholder="Supplier name" required/><Input name="contact" placeholder="Contact person"/><Input name="phone" placeholder="Phone"/><Input name="email" type="email" placeholder="Email"/><Input name="terms" placeholder="Payment terms"/><div><Button type="submit">Add supplier</Button></div></form></ComponentCard>
    <ComponentCard title="Create purchase order" desc="Order an existing product variant; receiving it updates inventory and purchase cost."><form action={createPurchaseOrder} className="grid gap-4 md:grid-cols-5 md:items-end"><select name="vendorId" required className="h-11 rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900"><option value="">Supplier</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select name="variantId" required className="h-11 rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900"><option value="">Product variant</option>{variants.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select><Input name="quantity" type="number" min={1} placeholder="Quantity" required/><Input name="unitCost" type="number" min={0} placeholder="Unit cost (KSh)" required/><Input name="expectedAt" type="date"/><Button type="submit">Create PO</Button></form></ComponentCard>
    <ComponentCard title="Record supplier payment" desc="Record an external settlement and reduce the supplier balance."><form action={recordVendorPayment} className="grid gap-4 md:grid-cols-4 md:items-end"><select name="vendorId" required className="h-11 rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900"><option value="">Supplier</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><Input name="amount" type="number" min={1} placeholder="Amount (KSh)" required/><Input name="reference" placeholder="Payment reference" required/><Button type="submit">Record payment</Button></form></ComponentCard>
    <BasicTableOne title="Suppliers" description="Search suppliers, catalogue coverage, terms, and outstanding balances." actions={<form className="flex gap-2"><Input name="q" defaultValue={q} placeholder="Search suppliers"/><Button type="submit" size="sm" variant="outline">Search</Button></form>} columns={["Supplier","Contact","Phone / email","Products","Terms","Balance","Status"]} empty="No suppliers match this search." rows={vendors.map(v => [<span key="n" className="font-medium text-gray-800">{v.name}</span>,v.contact_name??"—",v.phone??v.email??"—",v.products,v.payment_terms??"—",money.format(v.balance_minor),<Badge key="s" size="sm" color={v.status==="ACTIVE"?"success":"warning"}>{v.status}</Badge>])}/>
    <BasicTableOne title="Purchase orders & restocking" description="Receiving a purchase order increases stock and records its latest purchase cost." columns={["PO","Supplier","Status","Total","Ordered","Expected","Action"]} empty="No purchase orders yet." rows={orders.map(o => [o.po_number,o.vendor,<Badge key="s" size="sm" color={o.status==="RECEIVED"?"success":"warning"}>{o.status.replaceAll("_"," ")}</Badge>,money.format(o.total_minor),o.ordered_at?.toLocaleDateString("en-KE")??"Draft",o.expected_at?.toLocaleDateString("en-KE")??"—",o.status==="RECEIVED"?"Stock received":<form key="a" action={receivePurchaseOrder.bind(null,o.id)}><Button type="submit" size="sm" variant="outline">Receive stock</Button></form>])}/>
    <BasicTableOne title="Supplier payments" description="Latest settlements and their references." columns={["Supplier","Reference","Amount","Status","Paid"]} empty="No supplier payments recorded." rows={payments.map(p => [p.vendor,p.reference??"—",money.format(p.amount_minor),p.status,p.paid_at?.toLocaleDateString("en-KE")??"—"])}/>
  </div>;
}
