import ComponentCard from "@/components/common/ComponentCard";
import Input from "@/components/form/input/InputField";
import BasicTableOne from "@/components/tables/BasicTableOne";
import Badge from "@/components/ui/badge/Badge";
import Button from "@/components/ui/button/Button";
import { sql } from "@/server/db";
import { createStaffUser,setStaffStatus } from "../actions";

export const dynamic="force-dynamic";
export default async function StaffPage(){const staff=await sql<{id:string;username:string|null;display_name:string|null;role:string;status:string;permissions:Record<string,boolean>;last_login_at:Date|null}[]>`SELECT u.id,u.username,u.display_name,u.role::text,u.status::text,c.permissions,u.last_login_at FROM users u JOIN admin_credentials c ON c.user_id=u.id WHERE u.role IN('ADMIN','SUPPORT') ORDER BY u.created_at`;return <div className="space-y-6"><ComponentCard title="Add admin user" desc="Admin has full control. Operations/support can run day-to-day store operations but cannot create staff accounts."><form action={createStaffUser} className="grid gap-4 md:grid-cols-5 md:items-end"><Input name="displayName" placeholder="Display name" required/><Input name="username" placeholder="Username" required/><Input name="password" type="password" minLength={8} placeholder="Temporary password" required/><select name="role" className="h-11 rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900"><option value="SUPPORT">Operations / support</option><option value="ADMIN">Administrator</option></select><Button type="submit">Add staff user</Button></form></ComponentCard><BasicTableOne title="Admin users & permissions" description="Separate username/password accounts for platform staff." columns={["Staff member","Username","Role","Permissions","Last sign-in","Status","Action"]} empty="No staff accounts configured." rows={staff.map(s=>[<span key="n" className="font-medium text-gray-800">{s.display_name??"Unnamed staff"}</span>,s.username??"—",s.role,s.permissions.all?"Full platform":Object.keys(s.permissions).filter(k=>s.permissions[k]).join(", ")||"Operations",s.last_login_at?.toLocaleString("en-KE")??"Never",<Badge key="s" size="sm" color={s.status==="ACTIVE"?"success":"warning"}>{s.status}</Badge>,<form key="a" action={setStaffStatus.bind(null,s.id,s.status!=="ACTIVE")}><Button type="submit" size="sm" variant="outline">{s.status==="ACTIVE"?"Disable":"Reactivate"}</Button></form>])}/></div>}
